host_parasite_network: host_parasite_network.cpp
	g++ -Wall -g -o host_parasite_network host_parasite_network.cpp -lgsl -lgslcblas -lm
	
all:	host_parasite_network

clean:
	rm -f host_parasite_network
